package com.example.genealogy.model;

import lombok.Data;
import jakarta.persistence.*;

import java.util.Set;

@Entity
@Table(name = "Users")
@Data
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // IDs automatically generated by database
    private long id;

    @ManyToOne
    @JoinColumn(name="idrole")
    private Role idRole;

    @Column(name="username", length = 64)
    private String userName;

    @Column(name="password", length = 256)
    private String password;

    @Column(name="mail", columnDefinition = "text")
    private String mail;

    @OneToMany(mappedBy = "owner")
    private Set<Document> documents;

    @OneToMany(mappedBy = "user")
    private Set<Notification> notifications;

    @OneToMany(mappedBy = "user")
    private Set<PhysicalLocations> physicalLocations;
}
